### ISSUE TITLE
Support interpolate, step and case expressions for color and number values

### ISSUE THREAD

**Issue by mvarendorff** [greensopinion/dart-vector-tile-renderer#1]
Values like these:
```
'fill-opacity': [
  'interpolate',
  ['linear'],
  ['zoom'],
  0,
  1,
  15.5,
  1,
  16,
  0,
  22,
  0
],
```
currently just return null because they are nether a map nor a number:

https://github.com/greensopinion/dart-vector-tile-renderer/blob/434f11ab859a5aefce271638988b1ea33d3bd996/lib/src/themes/paint_factory.dart#L72-L84

Color values are handled in the same way.

I am willing to work on this (and already started fiddling around a bit), if you don't mind!

Disclaimer: I am doing this for one of our client projects and will likely only cover the things we "need" (like linear interpolation, while not implementing exponential) but also try my best to create groundwork that makes adding more functionality easier.

**Comment by greensopinion** [comment]
Fantastic - feel free to contribute via a pull request!

> I am doing this for one of our client projects and will likely only cover the things we "need"

Of course, I wouldn't expect to contribute anything that I didn't need either. :D

**Comment by greensopinion** [comment]
Closing this one off since it's stale. Feel free to open a PR if/when it makes sense.
