### ISSUE TITLE
TileProviders with Json sources instead of directly to pbf/image files

### ISSUE THREAD

**Issue by 1075dn** [greensopinion/dart-vector-tile-renderer#32]
What should be done with a Map Style like [this](https://github.com/IsraelHikingMap/VectorMap/blob/master/Styles/IHM.json), which link to sources that are Json files too, which show the correct way to access the data (pbf/image) files ([example](https://israelhiking.osm.org.il/vector/data/IHM.json))?

I tried using the `urlTemplate`s given in the secondary Json sources (such as in the above example: `https://israelhiking.osm.org.il/vector/data/IHM/{z}/{x}/{y}.pbf`) instead of the Json files, but I get an `InvalidProtocolBufferException: Protocol message tag had invalid wire type.`.

Any ideas? Am I doing something wrong? (Thanks a lot for this great plugin, by the way)

**Comment by greensopinion** [comment]
If you open the json file in a web browser, you'll find the URL template to use for vector tiles.

e.g.

```
    "IHM": {
      "type": "vector",
      "url": "https://israelhiking.osm.org.il/vector/data/IHM.json"
    },
```

if you look at https://israelhiking.osm.org.il/vector/data/TerrainRGB.json you'll find:

```
"tiles":["https://israelhiking.osm.org.il/vector/data/IHM/{z}/{x}/{y}.pbf"]
```

From there the `urlTemplate` is `https://israelhiking.osm.org.il/vector/data/IHM/{z}/{x}/{y}.pbf`

good luck!
