### ISSUE TITLE
improve web platform compatibility

### ISSUE THREAD

**Issue by greensopinion** [greensopinion/dart-vector-tile-renderer#55]
https://github.com/saigontek/dart-vector-tile/pull/10

**Comment by greensopinion** [comment]
I hacked together something that works https://github.com/greensopinion/flutter-vector-map-tiles/pull/77
Unfortunately it's so slow it's almost unusable. Not sure if this is worth pursuing further.

@ibrierley @blaugold

**Comment by greensopinion** [comment]
A screenshot showing it in action:

<img width="1312" alt="Screen Shot 2022-07-27 at 8 51 34 PM" src="https://user-images.githubusercontent.com/18102398/181416985-732c2bc5-6838-4d59-bea1-35dc61ff2ab4.png">

**Comment by blaugold** [comment]
Cool that you got it working! I tried it out and yeah, performance is not great. 😄 
Maybe we revisit the topic when Flutter supports compiling to WASM.

**Comment by maxhochlenertarnoldnextg** [comment]
Since flutter wasm support is now stable ( https://docs.flutter.dev/platform-integration/web/wasm ), does anyone want to try this again?
