### ISSUE TITLE
Rendering on web looks broken

### ISSUE THREAD

**Issue by blaugold** [greensopinion/dart-vector-tile-renderer#7]
This is the example app, viewed in chrome:

![Screenshot 2022-01-02 at 12 06 28](https://user-images.githubusercontent.com/5929595/147873812-26d303c3-e5c6-48c9-8c25-a170319d4918.png)

And here viewed in safari:

![Screenshot 2022-01-02 at 12 10 31](https://user-images.githubusercontent.com/5929595/147873917-237d442b-7f8a-4434-a112-3fa4bcdfd14e.png)

Maybe this is related to differences in handling of floating-point numbers between the Dart VM and JS engines.

**Comment by greensopinion** [comment]
Web is not a targeted platform at the moment, in part because of the issue that you discovered, but also because there are a lot of full-featured slippy map libraries in JavaScript (e.g. [maplibre-gl-js](https://github.com/maplibre/maplibre-gl-js), [Leaflet](https://leafletjs.com/), [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js))

Feel free to pursue this one further if it's important to you since it would be great if we could support web without a lot of effort.

**Comment by blaugold** [comment]
It's not a priority for me either, at the moment, but it would be nice to have it work at some point.

**Comment by greensopinion** [comment]
Since we're not planning on tackling this now, closing.

**Comment by ibrierley** [comment]
Just out of interest, is there a description of the Flutter floating point/vm issue out there ? Would be interested to have a read to understand it. I've seen this before, and can't for the life of me remember what I did (if anything).

**Comment by blaugold** [comment]
I didn't have any specific issue in mind. It just looks like some kind of numeric issue. 

Flutter uses this discrepancy between the Dart VM and JS for [`kIsWeb`](https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html):

```
const bool kIsWeb = identical(0, 0.0);
```

I guess it's possible that there are other differences that are a factor here.

**Comment by blaugold** [comment]
@ibrierley Thanks for looking into this. That was really helpful.

I found that XOR with negative numbers has different results in the Dart VM and in Dart compiled to JS. I've opened an issue for this (https://github.com/dart-lang/sdk/issues/49523).

**Comment by blaugold** [comment]
Turns out this is expected behavior, but there is a solution. I've created a PR (https://github.com/greensopinion/dart-vector-tile-renderer/pull/51).
