### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by JosefWN** [greensopinion/dart-vector-tile-renderer#70]
Hi, first of all, really cool project! Just tried out the `flutter_map` example with Mapbox and the Streets style.

I've seen some rendering issues:
- Zooming in/out causes the app to freeze/lag intermittently on my Macbook Air M1, raster thread is sometimes way above 3x frame budget, in the hundreds of milliseconds per frame even in smaller cities. As a stress test, try zooming in on Tokyo which has a lot of vectors densely packed. This is generally not an issue in other vector-based map renderers on my machine.
  - Could `canvas.save()` be somewhat expensive? I know `saveLayer` is, but not sure about `save`, as opposed to manipulating the coordinates rather than the canvas.
- Road signs are rendered without the signs themselves (only white text which is hard to read without any background), I'm guessing this is because of lacking support for raster layer types?
- Some labels are not rendered, for example the Baltimore label is never rendered, regardless of zoom level.
- If you strive for very similar looks, then I think highways and such (orange/yellow roads) have a thin white pixel border, similar to how text is rendered on the map.

Using Mapbox renderer:
<img width="425" alt="Screenshot 2022-11-11 at 13 57 39" src="https://user-images.githubusercontent.com/12534742/201346053-71dc13af-c5ec-4922-a4e6-cdd8dcdec2be.png">

Using `vector-tile-renderer`:
<img width="505" alt="Screenshot 2022-11-11 at 13 58 58" src="https://user-images.githubusercontent.com/12534742/201346074-423612cd-94b0-4499-924a-8b418e4e1353.png">

**Comment by greensopinion** [comment]
Thanks for the feedback!

Performance issues are definitely a challenge, especially in places that are data-rich such as Tokyo and LA. Did you run the app in release mode? The app makes use of isolates to improve frame rates, but only when run in release mode. 

> Road signs are rendered without the signs themselves (only white text which is hard to read without any background), I'm guessing this is because of lacking support for raster layer types?

That's right, the library doesn't have support for road signs yet.

> Some labels are not rendered, for example the Baltimore label is never rendered, regardless of zoom level.

I'm not sure why that's happening.

> If you strive for very similar looks, then I think highways and such (orange/yellow roads) have a thin white pixel border, similar to how text is rendered on the map.

It's possible that there is some unsupported syntax in the theme that you're using. You can find out about that by giving the theme reader a logger, you will see log output for each unsupported expression.

Feel free to make improvements!

**Comment by JosefWN** [comment]
> Performance issues are definitely a challenge, especially in places that are data-rich such as Tokyo and LA. Did you run the app in release mode? The app makes use of isolates to improve frame rates, but only when run in release mode.

Tried both, maybe it will get better once Impeller is released. I've noticed Flutter/Skia struggle more on macOS/iOS than on Windows for example (although I haven't tried out this library specifically on other platforms than macOS).

> Feel free to make improvements!

Cool!  Will do if I start using the lib, currently just playing around :)

**Comment by ibrierley** [comment]
Also be aware skia is typically pretty slow on drawing scaled paths > 1px, and I assume most other implementations also use opengl when it comes to the lag issues (so it would be interesting if any of those lag free implementations don't use opengl behind the scenes). I am a little out of touch in recent developments though!

**Comment by greensopinion** [comment]
Closing since there's nothing actionable here.
