### ISSUE TITLE
[Feature] Support optional rotation for non line labels like city, area, country etc.

### ISSUE THREAD

**Issue by sikandernoori** [greensopinion/dart-vector-tile-renderer#76]
[Since ](https://github.com/greensopinion/flutter-vector-map-tiles/issues/132)

**Comment by greensopinion** [comment]
fixed by c42c0ee21f67ec7fc0808000c8507aeb85dc6650

**Comment by greensopinion** [comment]
fixed by 17c50b59ba669c80f51af4c09e98d0fedfa4e4bf
