### ISSUE TITLE
hybrid maps?

### ISSUE THREAD

**Issue by sqcsabbey** [greensopinion/dart-vector-tile-renderer#87]
Are hybrid maps supported? I'm trying to switch between a few styles, including mapbox/satellite-streets-v12; that one has both a raster layer and a vector layer, from the stylesheet:

```
"sources": {
  "mapbox-satellite": {
    "url": "mapbox://mapbox.satellite",
    "type": "raster",
    "tileSize": 256
  },
  "composite": {
    "url": "mapbox://mapbox.mapbox-streets-v8",
    "type": "vector"
  }
},
```

If not directly supported, any suggestions about how to implement this? We're switching between vector tilesets and this, so I think I could add a separate layer to the map when this style is active, but I thought there might be a more consolidated solution.

Edit: is this more of a question for the vector_map_tiles project?

Edit 2: Is showing a raster base layer a possibility? In the changelog, v. 1.1.25 says:

> support multiple tile sources so that data such as hillshade can be rendered on a map

... can we do transparent backgrounds with this package? From that changelog comment, and a [couple](https://github.com/greensopinion/flutter-vector-map-tiles/issues/98) [issues](https://github.com/greensopinion/flutter-vector-map-tiles/issues/118), I wasn't so sure.

**Comment by greensopinion** [comment]
I've provided a multi-layer example: https://github.com/greensopinion/flutter-vector-map-tiles-examples
See https://github.com/greensopinion/flutter-vector-map-tiles-examples/blob/main/lib/examples/multi_layer.dart for details.
