### ISSUE TITLE
Upgrade `vector-tile` dependency

### ISSUE THREAD

**Issue by vkammerer** [greensopinion/dart-vector-tile-renderer#92]
https://github.com/bahung1221/dart-vector-tile/pull/13 was just merged, and a new major version of `vector-tile` was published:
https://pub.dev/packages/vector_tile

Could we upgrade to `vector-tile: ^2.0.0`?

This would enable consumers of this library to work with `protobuf: ^3.0.0`

**Comment by greensopinion** [comment]
updated
